spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobcy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  app:
    image:
      bucket: /Users/admin/Desktop/jobcy/images
